spring.application.name=BackendBanking
spring.data.mongodb.uri=mongodb://localhost:27017/banking_db
#spring.data.mongodb.uri=mongodb://localhost:27017/banking_db?retryWrites=true

#recaptcha.secret=6LeEcRwtAAAAAH0QhQbbxqvHuRxUerAaj0vkQwuj
recaptcha.secret=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe